name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.3', '8.4']
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: Run PHPUnit (PHPUnit 12)
        run: php -d xdebug.mode=off vendor/bin/phpunit --colors=always
      - name: Static Analysis (Psalm)
        if: always()
        run: php -d xdebug.mode=off vendor/bin/psalm --no-cache --output-format=github
      - name: Coding Style (PHP-CS-Fixer version)
        if: always()
        run: vendor/bin/php-cs-fixer --version

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: composer:v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: Static Analysis (Psalm)
        run: php -d xdebug.mode=off vendor/bin/psalm --no-cache --output-format=github
